server {
	listen 80;
	listen [::]:80;

	server_name db.dataklip.com;
	
	location / {
		proxy_pass http://127.0.0.1:5432;
	}

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dataklip.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dataklip.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    server_name dataklip.com www.dataklip.com;

    listen 80;
    listen [::]:80;
    
    return 301 https://dataklip.com$request_uri;
}

server {
    server_name dataklip.com www.dataklip.com;
	
    location / {
        proxy_pass http://127.0.0.1:3002;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dataklip.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dataklip.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

