server {
    server_name fooboo.bar www.fooboo.bar wiki.fooboo.bar;

    listen 80;
    listen [::]:80;
    
    return 301 https://fooboo.bar$request_uri;
}

server {
    server_name fooboo.bar www.fooboo.bar wiki.fooboo.bar;
	
    location / {
        proxy_pass http://127.0.0.1:3333;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/fooboo.bar/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/fooboo.bar/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

